import { cookies } from "next/headers";
import TanStackProvider from "@/components/TanStackProvider/TanStackProvider";
import Header from "@/components/Header/Header";
import "./globals.css";
import { Lato, Comfortaa } from "next/font/google";
import Container from "@/components/Container/Container";

const fontsLato = Lato({
  variable: "--font-lato",
  subsets: ["latin"],
  weight: ["100", "300", "400", "700", "900"],
  display: "swap",
});

const fontsComfortaa = Comfortaa({
  variable: "--font-comfortaa",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  display: "swap",
});

export const metadata = {
  title: "Лелека",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default async function RootLayout({ children }: RootLayoutProps) {
  const cookieStore = await cookies();
  const token = cookieStore.get("auth_token");
  const isAuthenticated = !!token;

  return (
    <html lang="uk">
      <body className={`${fontsLato.variable} ${fontsComfortaa.variable}`}>
        <TanStackProvider>
          <Header initialAuthStatus={isAuthenticated} />
          <main style={{ flex: 1, padding: "20px 0" }}>
            <Container>{children}</Container>
          </main>
        </TanStackProvider>
      </body>
    </html>
  );
}
