import type { Metadata } from "next";
import { Lato, Comfortaa } from "next/font/google";
import "./globals.css";
import TanStackProvider from "@/components/TanStackProvider/TanStackProvider";
import { BreadcrumbsGuard } from "@/components/Breadcrumbs";

const fontsLato = Lato({
  variable: "--font-lato",
  subsets: ["latin"],
  weight: ["100", "300", "400", "700", "900"],
  display: "swap",
});

const fontsComfortaa = Comfortaa({
  variable: "--font-comfortaa",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Лелека",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${fontsLato.variable} ${fontsComfortaa.variable}`}>
        <TanStackProvider>
          <BreadcrumbsGuard homeLabel="Лелека" capitalize />
          <main>{children}</main>
        </TanStackProvider>
      </body>
    </html>
  );
}
